site_name: Lice2 - Generate your license files with ease

# default to using the material theme
theme:
  name: material
  palette:
    primary: light-blue
    accent: blue
  features:
    - navigation.footer
    - navigation.expand

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seapagan/lice2
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gnramsay_dev

copyright: © 2024 Grant Ramsay (Seapagan)

repo_name: lice2
repo_url: https://github.com/seapagan/lice2

# default plugins here are to minify the html, css and js plus enable the search
# plugin. Adjust to your liking.
plugins:
  - search
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true

# edit these MARKDOWN extensions to your liking
markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: false
      auto_title: false
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Installation: installation.md
  - Overview: overview.md
  - Usage: usage.md
  - Configuration: configuration.md
  - Integration: integration.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - Future Plans: future_plans.md

extra_css:
  - css/extra.css
